### ISSUE TITLE
[FO4] Wrye Bash is unable to see string files from official DLC

### ISSUE THREAD

**Issue by Arthmoor** [wrye-bash/wrye-bash#294]
Just like with Skyrim, Bethesda included the string files for the Automatron DLC inside the archive files. This would not be a problem except that Fallout 4 has changed archive formats and the BSA reader will no longer work for that. BA2 files require a different format to be read to be able to see the files inside them.

I'm not sure what all needs to be done to work with this, but the TES5Edit code for the Fallout 4 branch has the ability to read these files since the strings are displayed correctly there for the official DLC (and main game too).

**Comment by Sharlikran** [comment]
Thanks for posting this Arthmoor.  I am going to talk to Zilav and Hlp and see what they did to make it work.  There is a chance that the BA2 file format hasn't changed much.  I know the format changed for how textures are stored in the BA2 files.  Since Wrye Flash just needs to read the header or strings files it may not be much of a change.

However, it is a DLL [libbsa](https://github.com/WrinklyNinja/libbsa) that WrinklyNinja wrote so not sure what will need to be done.  He is working on other things and really doesn't work on Wrye anymore but he does support his files.

**Comment by DontBlnkBadWolf** [comment]
Any update? Someone would think that after almost 8 months since FO4 was released that this would actually be working by now

**Comment by Sharlikran** [comment]
Utumno is only one volunteer working on the project.  #296 talked about adding BA2 support and that was never completed.  For now the work around is to extract the strings files.

**Comment by Utumno** [comment]
This is closed by b199a7bd5eec69ec0852f86d6e3629784e6b90ce and anyway duplicates #296 which is the master issue concerning Ba2 support. @Arthmoor please verify

What remains to be done is _unpack_ those strings

**Comment by Sharlikran** [comment]
Wrinklyninja said his BSA dll currently included doesn't unpack the files.  Do you know if Wrye Bash for clasic Skyrim unpacks the BSA while making a Bashed Patch?  If not maybe unpacking the files isn't needed and simply reading them is sufficient?

**Comment by Utumno** [comment]
The code unpacks the bsas yes. Don't know if needed I guess yes otherwise people would have avoided it.

I still need confirmation for fallout4

**Comment by Sharlikran** [comment]
Okay I'm going to church and I'll work on things when I get back.  Talk to you later.  Get some rest I suspect you are in  a different time zone.  ;)

**Comment by Arthmoor** [comment]
Bash is still unable to see the string files while they're inside BA2 files.

I don't think they need to be unpacked, just be able to read them the way SSE is now doing.

**Comment by Utumno** [comment]
Still unable ? Grr

Where are those strings supposed to be ? Which ba2 ? Will look into that asap

**Comment by Arthmoor** [comment]
They're inside Fallout4 - Interface.ba2

**Comment by Utumno** [comment]
Ok will bend them to my will tommorowishzzzzz

**Comment by Arthmoor** [comment]
The other ones are inside the DLC ba2 files.

**Comment by Utumno** [comment]
Well I got it - Bash looks for bsas in those two ini settings:

for key in (u'sResourceArchiveList', u'sResourceArchiveList2'):

This has to be modified for fallout4 - what should it read ? Keep in mind that Bash loads the bsas in there and we should avoid loading all of them (memory inefficient) - so we probably should modify this for skyrim too.

These are the keys is I see in vanilla fallout:

```
sResourceIndexFileList=Fallout4 - Textures1.ba2, Fallout4 - Textures2.ba2, Fallout4 - Textures3.ba2, Fallout4 - Textures4.ba2, Fallout4 - Textures5.ba2, Fallout4 - Textures6.ba2, Fallout4 - Textures7.ba2, Fallout4 - Textures8.ba2, Fallout4 - Textures9.ba2
sResourceStartUpArchiveList=Fallout4 - Startup.ba2, Fallout4 - Shaders.ba2, Fallout4 - Interface.ba2
SResourceArchiveList=Fallout4 - Voices.ba2, Fallout4 - Meshes.ba2, Fallout4 - MeshesExtra.ba2, Fallout4 - Misc.ba2, Fallout4 - Sounds.ba2, Fallout4 - Materials.ba2
SResourceArchiveList2=Fallout4 - Animations.ba2
sResourceDataDirsFinal=STRINGS\
SGeometryPackageList=Fallout4 - Geometry.csg
SCellResourceIndexFileList=Fallout4.cdx
SResourceArchiveMemoryCacheList= Fallout4 - Misc.ba2, Fallout4 - Shaders.ba2, Fallout4 - Interface.ba2, Fallout4 - Materials.ba2
```

So I should probably add sResourceStartUpArchiveList - but this will result in unnecessary loading Fallout4 - Startup.ba2, Fallout4 - Shaders.ba2, 

I need a run down of those and related keys so I check all relevant keys and only those - or I should probably hardcode the bsas for the master files ? But what about mods ?

**Comment by Arthmoor** [comment]
Well you'll probably need a hard list of BSAs for that anyway since the DLC files keep their strings inside their own files and they're never added to those archive lists.

Not sure how you're accounting for it in Skyrim and SSE but it's basically the same idea for those games too.

**Comment by Utumno** [comment]
> Not sure how you're accounting for it in Skyrim and SSE but it's basically the same idea for those games too.

Same code

I need a rundown of:

- strings for master esm - wherew are they for all games
- mod inis - I guess they define their bsas in u'sResourceArchiveList', u'sResourceArchiveList2' for skyrim - for fallout4 ?
- dlcs - if their stings are in dlcname.bsa then it's ok as Bash always also looks for a bsa bamed as the mod

(when I say bsa I mean also ba2)

**Comment by Arthmoor** [comment]
String files are located in the following places:

For Classic Skyrim:

Skyrim - Interface.bsa
Dawnguard.bsa
Hearthfires.bsa
Dragonborn.bsa

Data\Strings\Skyrim_English.DLSTRINGS
Data\Strings\Skyrim_English.ILSTRINGS
Data\Strings\Skyrim_English.STRINGS
Data\Strings\Update_English.DLSTRINGS
Data\Strings\Update_English.ILSTRINGS
Data\Strings\Update_English.STRINGS

(Yes, the ones for official patches were delivered loose, fun times)

For Special Edition:

All strings are stored in Skyrim - Interface.bsa, including the ones for the DLCs. None are shipped as loose files.

For Fallout 4:

Main game stores them in Fallout4 - Interface.ba2.

DLCs each store them in [DLCName] - Main.ba2.

None were ever shipped as loose files.

**Comment by InsanePlumber** [comment]
String files are also located in "Skyrim - Patch.bsa" which was updated in November 10.
And it is last on the BSA list "sResourceArchiveList2"

**Comment by Utumno** [comment]
Thanks @Arthmoor and @InsanePlumber 

What about mod inis ?

> mod inis - I guess they define their bsas in u'sResourceArchiveList', u'sResourceArchiveList2' for skyrim - for fallout4 ?

**Comment by Sharlikran** [comment]
Check your Bethesda PM please.

**Comment by Arthmoor** [comment]
Mods don't need ini fragments. They can load strings via their assigned BSA files if they have them. A vanishingly small number of mods bother to include string files at all.

**Comment by Utumno** [comment]
So `for key in (u'sResourceArchiveList', u'sResourceArchiveList2'):` is really for loading the bsas for the game esms ? In that case I could replace this with per game definitions of bsa files that have strings for the vanilla esms
 But this has the disadvantage that if new patches add strings in a different bsa (see "Skyrim - Patch.bsa") then that won't be detected by simply adding it to the ini
Has the advantage that I won't need to load all the bsas in there (fater and less memory)

What should I do you think ?

**Comment by Arthmoor** [comment]
I doubt very much Bethesda is going to start spreading strings into more files than they have already. IMO, I'd go with the dedicated lists. They're all in known locations so it shouldn't be a problem.

**Comment by Utumno** [comment]
@Arthmoor (or anyone):

I need:

- names of Falout4 DLCs that have strings. Last FO4 version I saw files for had no DLC -Main.ba2 files
- the numbers of the latest patches for the games we support - since strings (and other stuff) are version dependent we should make clear in front page readme which version of the games we support

**Comment by Utumno** [comment]
Also - since the code supports mod inis I want this left in for non vanilla mods. Do Fallout4 and skyrim se support game inis like Skyrim ?

**Comment by Arthmoor** [comment]
DLC string files are in the following:

Far Harbor: DLCCoast - Main.ba2
Nuka-World: DLCNukaWorld - Main.ba2
Automatron: DLCRobot - Main.ba2
Wasteland Workshop: DLCworkshop01 - Main.ba2
Contraptions Workshop: DLCworkshop02 - Main.ba2
Vault-Tec Workshop: DLCworkshop03 - Main.ba2

Current patch level for Fallout 4 is 1.8.7.0.
Current patch for SSE: 1.2.39.0.8.
Current patch for Classic Skyrim: 1.9.32.0.8. (Highly unlikely to ever change again)

That mods support ini fragments shouldn't really matter. Anyone inserting an archive list into those is going to be causing serious problems for other people and encouraging that kind of thing seems unwise.

SSE supports them, USSEP is using one, though not for archive purposes. I'm not sure if Fallout 4 does or not because I haven't tried it yet.

**Comment by Utumno** [comment]
Ok I pushed some commits in utumno-wip that should fix this - please test

**Comment by Arthmoor** [comment]
Everything continues to be ok for Skyrim and SSE, but Fallout 4 still doesn't see the string files at all.

**Comment by Utumno** [comment]
Well what I missed was that in ba2 the filenames were not all lowercase - should work now.

Btw - where are the strings for Update.esm in skyrim and skyrimSE ?

**Comment by Sharlikran** [comment]
Skyrim SE: All strings files are in Skyrim - Patch.bsa
Classic Skyrim: Strings files for Skyrin.esm and Update.esm are loose files in the Strings folder installed by Steam.  The rest are the BSA files matching the name of the DLC or plugin.

**Comment by Utumno** [comment]
To properly close this I still miss if F4 supports game inis - anyone ?

**Comment by Arthmoor** [comment]
Yep. It appears to support ini fragments too, in the form of <plugin name>.ini matching up to <plugin name>.esp

**Comment by Utumno** [comment]
Thanks @Arthmoor - same system as skyrim I guess.

One final - we search for string files in skyrim in (u'sResourceArchiveList', u'sResourceArchiveList2') - one of the reasons this failed to find string files in F4 is that apparently the fallout 4 ini contains a bunch of keys:

```
[Archive]
sResourceIndexFileList=Fallout4 - Textures1.ba2, Fallout4 - Textures2.ba2, Fallout4 - Textures3.ba2, Fallout4 - Textures4.ba2, Fallout4 - Textures5.ba2, Fallout4 - Textures6.ba2, Fallout4 - Textures7.ba2, Fallout4 - Textures8.ba2, Fallout4 - Textures9.ba2
sResourceStartUpArchiveList=Fallout4 - Startup.ba2, Fallout4 - Shaders.ba2, Fallout4 - Interface.ba2
SResourceArchiveList=Fallout4 - Voices.ba2, Fallout4 - Meshes.ba2, Fallout4 - MeshesExtra.ba2, Fallout4 - Misc.ba2, Fallout4 - Sounds.ba2, Fallout4 - Materials.ba2
SResourceArchiveList2=Fallout4 - Animations.ba2
sResourceDataDirsFinal=STRINGS\, TEXTURES\, MUSIC\, SOUND\, INTERFACE\, MESHES\, PROGRAMS\, MATERIALS\, LODSETTINGS\, VIS\, MISC\, SCRIPTS\, SHADERSFX\
SGeometryPackageList=Fallout4 - Geometry.csg
SCellResourceIndexFileList=Fallout4.cdx
SResourceArchiveMemoryCacheList= Fallout4 - Misc.ba2, Fallout4 - Shaders.ba2, Fallout4 - Interface.ba2, Fallout4 - Materials.ba2
```

As seen the string files ba2 (that is Fallout4 - Interface.ba2) appears in two new keys SResourceArchiveMemoryCacheList and sResourceStartUpArchiveList. I should extend the keys for fallout4 but which of those should I include ? String support for the vanilla esm and dlcs is now hardcoded but still to finish this up I would like to have per game keys - (u'sResourceArchiveList', u'sResourceArchiveList2') seem to be enough for skyrim but what shouls I add for fallout4 ?

Will merge the rest of the changes but would like to have this answered soonish.

**Comment by Utumno** [comment]
Closed this as the main problem is solved but I still need feedback on the points above

And a last technical detail: does the order of the _values_ in the Archive keys matter ?
