### ISSUE TITLE
Case-sensitivity issue in Wizard INI tweak creation

### ISSUE THREAD

**Issue by alphaniner** [wrye-bash/wrye-bash#443]
A line such as the following in a wizard:

`EditINI('file.ini', 'setGS', 'setting', <value>)`

Creates the following INI tweak:
```
[setGS]
setting=<value>
```

Rather than a 'batch-style' tweak as expected.

Case doesn't seem to make a difference; eg. if the second argument to EditINI() is 'setgs' it just changes the case in the section heading.

Changing the following line in Mopy/bash/belt.py:
```
        elif realSection == u']setgs[':`
```

to:
```
        elif realSection == u']setGS[':
```

Results in the expected type of tweak being generated regardless of the case of 'setgs' passed to EditINI(). IIRC the console is case-insensitive so I think this is fine.

[BashBugDump.log](https://github.com/wrye-bash/wrye-bash/files/3384762/BashBugDump.log) for version and OS info, it doesn't contain any info related to the problem.

**Comment by Utumno** [comment]
fixes pushed for this and 444 on nightly - give them a whirl!

**Comment by alphaniner** [comment]
Sorry, I just updated today. The fix for 444 is good, but I still get game-ini style tweaks with setGS. The problem is still related to case, albeit in a much more complicated way. I found three work-arounds, hopefully they will lead you to a valid solution.

The immediate problem is that line 360 in belt.py
```
modFormat = values[0] + _obse_mod_formats[realSection]
```
raises `KeyError` (same for line 361 FWIW).

This has something to do with the fact that the value of `realSection` is a `CIstr` (`<class 'bash.bolt.CIstr'>`), because the dictionary provided to `generateTweakLines` as the `wizardEdits` argument is a `LowerDict` (belt.py line 1132). FWIW I don't see the point in this being a `LowerDict` rather than a `dict`, and a proper tweak is created if it's changed.

Supposing I'm wrong about that, though...

The fact that `realSection` is a `CIstr` doesn't immediately explain why 'set' edits work but 'setGS' edits don't. The only difference I could see is that ']set[' contains only lowercase characters whereas ']setGS[' contains both lower- and upper-case. To see if this was the cause, I changed the keys in `_obse_mod_formats` (belt.py line 345) and `_obse_del_formats` (belt.py line 348) to `u']setgs['` and the value of the `u'setGS'` key in `ci_pseudosections` (bosh/ini_files.py line 407) to `u']setgs['`, and a proper tweak was created.

Finally, a proper tweak is created if `realSection` is changed to a normal string in lines 360 & 361 of belt.py:
```
modFormat = values[0] + _obse_mod_formats[str(realSection)]
delFormat = u';-' + values[0] + _obse_del_formats[str(realSection)]
```

**Comment by Utumno** [comment]
Hey away from a windows machine but changing the `_obse_del_formats` and `_obse_mod_formats` to LowerDicts would solve this?

We need LowerDicts cause ini keys/sections are case insensitive

**Comment by alphaniner** [comment]
I see why `OBSEIniFile.ci_pseudosections` needs to be a LowerDict, but not anything else.

With the first work-around I still get a proper tweak with e.g.
```
EditINI("file.ini", "SeTgS", "setting", 42)
```
Granted the weird case is passed on to the tweak
```
SeTgS setting 42
```
but it looks like that would be the case regardless.

**Comment by alphaniner** [comment]
Anyway, I changed `_obse_del_formats` and `_obse_mod_formats` to LowerDict and that also resolves the issue, but FWIW it doesn't seem like the right way to handle the problem.

**Comment by Utumno** [comment]
Thanks for testing - it is, the whole ini handling needs be case insensitive I just was not aware what the wizardEdits type was, hence untested. Why it is it's beyond the scope of this issue :P

(hint: a9112d6761e47b1fc41aca53df1add5bdd41ad79)
